import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'
import { findMatchingProviderIds } from '@/lib/matchProviders'
import { sendLeadsToProviders } from '@/lib/sendLeadsToProviders'

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const supabase = createAdminClient()

    // 1. Create customer
    const { data: customer, error: custErr } = await supabase
      .from('customers')
      .insert({
        name: body.name,
        email: body.email,
        phone: body.phone || null,
        preferred_contact: body.preferred_contact || 'email',
      })
      .select()
      .single()

    if (custErr) throw custErr

    // Calculate offer deadline (24h for ASAP, 48h for all others)
    const isAsap = body.urgency === 'ASAP'
    const hoursOpen = isAsap ? 24 : 48
    const offersCloseAt = new Date(Date.now() + hoursOpen * 60 * 60 * 1000).toISOString()

    // 2. Create request (offer_token auto-generated by DB trigger)
    const { data: request, error: reqErr } = await supabase
      .from('transportation_requests')
      .insert({
        customer_id: customer.id,
        category: body.category,
        pickup_address: body.pickup_address,
        pickup_city: body.pickup_city || extractCity(body.pickup_address),
        pickup_zip: body.pickup_zip || extractZip(body.pickup_address),
        dropoff_address: body.dropoff_address,
        dropoff_city: body.dropoff_city || extractCity(body.dropoff_address),
        dropoff_zip: body.dropoff_zip || extractZip(body.dropoff_address),
        passenger_count: body.passenger_count || 1,
        passenger_age_grade: body.passenger_age_grade || null,
        trip_type: body.trip_type || 'recurring',
        days_needed: body.days_needed || null,
        pickup_time: body.pickup_time || null,
        return_time: body.return_time || null,
        start_date: body.start_date || null,
        duration: body.duration || null,
        wheelchair_accessible: body.wheelchair_accessible || false,
        car_seat_needed: body.car_seat_needed || false,
        medical_monitoring: body.medical_monitoring || false,
        aide_needed: body.aide_needed || false,
        shared_ride_ok: body.shared_ride_ok ?? true,
        private_only: body.private_only || false,
        multilingual_driver: body.multilingual_driver || false,
        background_checked: body.background_checked || false,
        special_notes: body.special_notes || null,
        budget_range: body.budget_range || null,
        urgency: body.urgency || null,
        how_did_you_hear: body.how_did_you_hear || null,
        offers_close_at: offersCloseAt,
        status: 'new',
      })
      .select()
      .single()

    if (reqErr) throw reqErr

    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://hiyoon.com'

    // 3. Find approved providers matching this request's category and area,
    // so leads go out automatically instead of waiting on an admin to send them.
    const matchingProviderIds = await findMatchingProviderIds(request)

    // 4. Send customer confirmation + admin notification + provider leads.
    // These are awaited (via Promise.allSettled) instead of fired-and-forgotten,
    // because Vercel serverless functions can freeze/terminate immediately after
    // the response is returned, which was silently dropping unawaited fetches.
    const [confirmationResult, adminNotifyResult, leadDispatchResult] = await Promise.allSettled([
      fetch(`${siteUrl}/api/notifications/customer-confirmation`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ customer, request }),
      }),
      fetch(`${siteUrl}/api/notifications/new-request`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ customer, request, matchedProviders: matchingProviderIds.length }),
      }),
      matchingProviderIds.length > 0
        ? sendLeadsToProviders({ requestId: request.id, providerIds: matchingProviderIds })
        : Promise.resolve(null),
    ])

    if (confirmationResult.status === 'rejected') {
      console.error('Customer confirmation email failed:', confirmationResult.reason)
    }
    if (adminNotifyResult.status === 'rejected') {
      console.error('Admin new-request notification failed:', adminNotifyResult.reason)
    }
    if (leadDispatchResult.status === 'rejected') {
      console.error('Automatic lead dispatch failed:', leadDispatchResult.reason)
    } else if (leadDispatchResult.value && 'error' in leadDispatchResult.value) {
      console.error('Automatic lead dispatch failed:', leadDispatchResult.value.error)
    }

    return NextResponse.json({
      success: true,
      matched_providers: matchingProviderIds.length,
      reference_number: request.reference_number,
      offer_token: request.offer_token,
      id: request.id,
    })
  } catch (error: unknown) {
    console.error('Request submission error:', error)
    return NextResponse.json(
      { error: 'Failed to submit request. Please try again.' },
      { status: 500 }
    )
  }
}

// Simple city/zip extractors from address strings
function extractCity(address: string): string | null {
  if (!address) return null
  const parts = address.split(',').map((p) => p.trim())
  if (parts.length >= 2) return parts[parts.length - 2] || null
  return null
}

function extractZip(address: string): string | null {
  if (!address) return null
  const match = address.match(/\b\d{5}\b/)
  return match ? match[0] : null
}

export async function GET(req: NextRequest) {
  try {
    const supabase = createAdminClient()
    const { searchParams } = new URL(req.url)
    const status = searchParams.get('status')
    const limit = parseInt(searchParams.get('limit') || '50')

    let query = supabase
      .from('transportation_requests')
      .select('*, customer:customers(*)')
      .order('created_at', { ascending: false })
      .limit(limit)

    if (status) query = query.eq('status', status)

    const { data, error } = await query
    if (error) throw error

    return NextResponse.json({ data })
  } catch (error: unknown) {
    return NextResponse.json({ error: 'Failed to fetch requests' }, { status: 500 })
  }
}
